# Generated by Django 4.2.3 on 2023-09-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="workflowinstance",
            name="status",
        ),
        migrations.AddField(
            model_name="taskdefinition",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="TaskInstance",
        ),
        migrations.AddField(
            model_name="context",
            name="workflow_instance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context",
                to="workflows.workflowinstance",
            ),
        ),
    ]
