# Generated by Django 4.2.3 on 2023-09-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0003_taskinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdefinition",
            name="dependencies",
            field=models.ManyToManyField(blank=True, to="workflows.taskdefinition"),
        ),
    ]
