# Generated by Django 4.2.5 on 2023-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0004_taskdefinition_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdefinition",
            name="operation",
            field=models.CharField(
                choices=[("AND", "AND"), ("OR", "OR")], default="AND", max_length=3
            ),
        ),
    ]
